server.port=8080

spring.application.name=backend
spring.datasource.url=jdbc:h2:mem:portfoliodb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USER:user}
spring.mail.password=${SMTP_PASS:pass}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cors.allowed-origins=${NEXT_PUBLIC_API_URL:http://localhost:3000}

github.api.url=https://api.github.com/users/pujan-X
github.api.token=${GITHUB_TOKEN:}
